#!/usr/bin/env python3
"""
run_sweep.py — Sequential automation of all 25 Innovus APR sweep runs.

Prerequisites:
  - All 4 synthesized netlists must exist before running:
      GCN.1400.syn.v  GCN.1000.syn.v  GCN.0800.syn.v  GCN.0600.syn.v
  - Set APR_DIR below to the directory containing innovus_flow.tcl.

Usage (from repo root on the server):
    python ppa-pilot/scripts/run_sweep.py            # full sweep
    python ppa-pilot/scripts/run_sweep.py --resume   # skip runs with existing summary.rpt
    python ppa-pilot/scripts/run_sweep.py --dry-run  # print plan without executing
"""

import argparse
import subprocess
import sys
import time
from pathlib import Path

# =============================================================================
# CONFIGURATION — set both paths before running on the server
# =============================================================================

APR_DIR   = Path("/path/to/GCN/flow/apr")   # directory containing innovus_flow.tcl
SYNTH_DIR = Path("/path/to/GCN/flow/syn/results")  # directory containing GCN.<clk>.syn.v

# =============================================================================
# SWEEP RUN DEFINITIONS
# =============================================================================

RUNS = [
    # ---- Phase 1: clk=1400 ps -------------------------------------------
    {"clk": 1400, "util": 0.50, "ar": 1.0, "cong": "low"   },  # 01 baseline
    {"clk": 1400, "util": 0.65, "ar": 1.0, "cong": "low"   },  # 02 util stress
    {"clk": 1400, "util": 0.70, "ar": 1.0, "cong": "low"   },  # 03 util boundary
    {"clk": 1400, "util": 0.40, "ar": 1.0, "cong": "low"   },  # 04 util easy
    {"clk": 1400, "util": 0.55, "ar": 1.0, "cong": "low"   },  # 05 util mid
    {"clk": 1400, "util": 0.50, "ar": 1.2, "cong": "low"   },  # 06 AR tall
    {"clk": 1400, "util": 0.50, "ar": 0.8, "cong": "low"   },  # 07 AR wide
    {"clk": 1400, "util": 0.50, "ar": 1.5, "cong": "low"   },  # 08 AR extreme
    {"clk": 1400, "util": 0.50, "ar": 1.0, "cong": "medium"},  # 09 cong medium
    {"clk": 1400, "util": 0.50, "ar": 1.0, "cong": "high"  },  # 10 cong high
    # ---- Phase 2: clk=1000 ps -------------------------------------------
    {"clk": 1000, "util": 0.50, "ar": 1.0, "cong": "low"   },  # 11
    {"clk": 1000, "util": 0.40, "ar": 1.0, "cong": "low"   },  # 12
    {"clk": 1000, "util": 0.55, "ar": 1.0, "cong": "low"   },  # 13
    {"clk": 1000, "util": 0.65, "ar": 1.0, "cong": "low"   },  # 14
    {"clk": 1000, "util": 0.70, "ar": 1.0, "cong": "low"   },  # 15
    # ---- Phase 3: clk=800 ps --------------------------------------------
    {"clk":  800, "util": 0.50, "ar": 1.0, "cong": "low"   },  # 16
    {"clk":  800, "util": 0.40, "ar": 1.0, "cong": "low"   },  # 17
    {"clk":  800, "util": 0.55, "ar": 1.0, "cong": "low"   },  # 18
    {"clk":  800, "util": 0.65, "ar": 1.0, "cong": "low"   },  # 19
    {"clk":  800, "util": 0.70, "ar": 1.0, "cong": "low"   },  # 20
    # ---- Phase 4: clk=600 ps --------------------------------------------
    {"clk":  600, "util": 0.50, "ar": 1.0, "cong": "low"   },  # 21
    {"clk":  600, "util": 0.40, "ar": 1.0, "cong": "low"   },  # 22
    {"clk":  600, "util": 0.55, "ar": 1.0, "cong": "low"   },  # 23
    {"clk":  600, "util": 0.65, "ar": 1.0, "cong": "low"   },  # 24
    {"clk":  600, "util": 0.70, "ar": 1.0, "cong": "low"   },  # 25
]


def run_dir_name(r: dict) -> str:
    return f"run_{r['clk']}_u{int(r['util']*100)}_ar{int(r['ar']*100)}_{r['cong']}"


def write_user_config(r: dict) -> None:
    # Default.globals sources ../user_config.tcl relative to the apr/ CWD,
    # which resolves to GCN/flow/user_config.tcl — one level above APR_DIR.
    cfg_path = APR_DIR.parent / "user_config.tcl"
    cfg_path.write_text(
        f"# Auto-generated by run_sweep.py\n"
        f"set synth_out_dir {SYNTH_DIR}\n"
        f"set clk_period    {r['clk']}\n"
        f"set util_target   {r['util']}\n"
        f"set aspect_ratio  {r['ar']}\n"
        f"set core_margin   5\n"
        f'set cong_effort   "{r["cong"]}"\n'
    )


def is_complete(r: dict) -> bool:
    name = run_dir_name(r)
    return (APR_DIR / "runs" / name / "reports" / "summary.rpt").exists()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--resume",  action="store_true",
                    help="Skip runs whose output directory already has summary.rpt")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print the full plan without executing anything")
    ap.add_argument("--limit",   type=int, default=None,
                    help="Stop after N runs (e.g. --limit 2 for a sanity check)")
    args = ap.parse_args()

    if not args.dry_run and not APR_DIR.exists():
        print(f"ERROR: APR_DIR not found: {APR_DIR}", file=sys.stderr)
        sys.exit(1)
    if not args.dry_run and not SYNTH_DIR.exists():
        print(f"ERROR: SYNTH_DIR not found: {SYNTH_DIR}", file=sys.stderr)
        sys.exit(1)

    log_dir = APR_DIR / "logs"
    if not args.dry_run:
        log_dir.mkdir(exist_ok=True)

    total  = len(RUNS)
    failed = []

    print(f"\n{'='*60}")
    print(f"  GCN Accelerator PPA Sweep — {total} runs")
    print(f"  APR_DIR   : {APR_DIR}")
    print(f"  SYNTH_DIR : {SYNTH_DIR}")
    print(f"  resume    : {args.resume}   dry-run : {args.dry_run}")
    print(f"{'='*60}\n")

    runs = RUNS[:args.limit] if args.limit else RUNS

    for i, r in enumerate(runs, 1):
        name = run_dir_name(r)
        print(f"[{i:02d}/{total}] {name}")

        if args.resume and is_complete(r):
            print("  [SKIP] summary.rpt exists")
            continue

        if args.dry_run:
            continue

        write_user_config(r)
        print(f"  user_config.tcl → clk={r['clk']} util={r['util']} ar={r['ar']} cong={r['cong']}")

        t0 = time.time()
        with open(log_dir / f"{name}.log", "w") as lf:
            ret = subprocess.run(
                ["innovus", "-batch", "-files", "innovus_flow.tcl",
                 "-log", f"logs/innovus_{name}"],
                cwd=str(APR_DIR),
                stdout=lf, stderr=subprocess.STDOUT
            ).returncode
        elapsed = (time.time() - t0) / 60

        if ret == 0:
            print(f"  [OK]      {elapsed:.0f} min  →  runs/{name}/")
        else:
            print(f"  [FAILED]  {elapsed:.0f} min  exit={ret}  check logs/{name}.log")
            failed.append(name)

    print(f"\n{'='*60}")
    print(f"  Done.  Attempted: {total - len(failed)}  Failed: {len(failed)}")
    if failed:
        for f in failed:
            print(f"    {f}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
